"""initial schema
Revision ID: ee2cfd67e633
Revises: 
Create Date: 2026-06-18 11:35:56.310881
"""
from alembic import op
import sqlalchemy as sa

revision = 'ee2cfd67e633'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_actor'), ['actor'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_ts'), ['ts'], unique=False)

    op.create_table('awards',
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('agency', sa.String(), nullable=False),
    sa.Column('vendor', sa.String(), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('vehicle', sa.String(), nullable=False),
    sa.Column('co', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('ref')
    )
    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_awards_agency'), ['agency'], unique=False)
        batch_op.create_index(batch_op.f('ix_awards_vendor'), ['vendor'], unique=False)

    op.create_table('opportunities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('agency', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('vehicle', sa.String(), nullable=False),
    sa.Column('cpv', sa.String(), nullable=False),
    sa.Column('value', sa.BigInteger(), nullable=False),
    sa.Column('close', sa.Date(), nullable=True),
    sa.Column('incumbent', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_agency'), ['agency'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_ref'), ['ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_vehicle'), ['vehicle'], unique=False)

    op.create_table('pursuits',
    sa.Column('opportunity_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('opportunity_id')
    )
    with op.batch_alter_table('pursuits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pursuits_stage'), ['stage'], unique=False)

    op.create_table('saved_searches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('query', sa.JSON(), nullable=False),
    sa.Column('alert', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('when', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('vendor_ontology',
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('company')
    )
    op.create_table('workflows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflows')
    op.drop_table('vendor_ontology')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('signals')
    op.drop_table('saved_searches')
    with op.batch_alter_table('pursuits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pursuits_stage'))

    op.drop_table('pursuits')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunities_vehicle'))
        batch_op.drop_index(batch_op.f('ix_opportunities_ref'))
        batch_op.drop_index(batch_op.f('ix_opportunities_market'))
        batch_op.drop_index(batch_op.f('ix_opportunities_agency'))

    op.drop_table('opportunities')
    with op.batch_alter_table('awards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_awards_vendor'))
        batch_op.drop_index(batch_op.f('ix_awards_agency'))

    op.drop_table('awards')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_log_actor'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
